### ISSUE TITLE
Un Nouveau test pour les villes

### ISSUE THREAD

**Issue by Ashura3342** [alexpwf/autocompletion_unitest#3]
[Dico]
Isle d'Espagnac, 34 square paragnac
Saint-Jacque de Compostelle, 120 rue Matignon
[Input]
d
1
[Output]
Saint-Jacque de Compostelle, 120 rue Matignon

**Comment by alexpwf** [comment]
fix: [Output]
{i} {s}
{1 :  Saint-Jacque DE Compostelle}
=> Saint-Jacque de Compostelle, 120 rue Matignon

**Comment by Ashura3342** [comment]
[Output]
{d} {c} {i} {s}
d
{1 :  saint-jacque DE compostelle}
1
=> Saint-Jacque de Compostelle, 120 rue Matignon

**Comment by Ashura3342** [comment]
Nouveau test :
[Dico]
DE de, 46 square machin
Dedo, 58 rue toto
[Input]
d
[Output]
{1 :  DE de}
d
=> Dedo, 58 rue toto
